### ISSUE TITLE
Add JavaScript benchmarks

### ISSUE THREAD

**Issue by domoritz** [ursacomputing/benchmarks#35]
We would love to run continuous benchmarks for the Arrow JS library. We already have a benchmark setup with benchmark.js at https://github.com/apache/arrow/blob/master/js/perf/index.js. It would be awesome if there was a native integration into Conbench for results from JavaScript benchmarks.

Could you help us set up the benchmarks for JavaScript?

Arrow ticket for Conbench integration: https://issues.apache.org/jira/browse/ARROW-12690

**Comment by domoritz** [comment]
Fantastic. Looking forward as well. I added some basic documentation for running the benchmarks in https://github.com/apache/arrow/pull/10291. Right now, the script simply runs some performance tests and prints the results like this

```
Running apache-arrow performance tests...

Parse "tracks":
Table.from
 x 11,396 ops/sec ±0.60% (92 runs sampled)
   avg: 0.09ms
   0.54% of a frame @ 60FPS

Parse "tracks":
readBatches
 x 11,533 ops/sec ±0.66% (96 runs sampled)
   avg: 0.09ms
   0.54% of a frame @ 60FPS
...
```

We could totally change this setup and instead run specific measurements based on a cli argument and return JSON. Can you give an example for what the minimum inputs and outputs are?

Happy to chat more when you have time to dive into JS perf tests.

**Comment by domoritz** [comment]
I added support for JSON output in https://github.com/apache/arrow/pull/10331. How does this look @dianaclarke?

**Comment by domoritz** [comment]
We now construct the benchmark data with JavaScript so no Python is needed anymore. Anything else we can help with @dianaclarke?

**Comment by dianaclarke** [comment]
@domoritz Apologies for not responding sooner. I've been working on better regression/improvement detection and it's taking me longer than expected, plus I was on vacation.

We'll still need a Python wrapper to hook it all up. Similar to the wrapper we have that executes the Arrow C++ benchmarks.

https://github.com/ursacomputing/benchmarks/blob/main/benchmarks/cpp_micro_benchmarks.py

I won't be able to work on this for a few weeks yet, but I'm happy to provide pointers if you want to give it a shot.

**Comment by domoritz** [comment]
Let's pick it up in a few weeks when we both have cycles available.

**Comment by domoritz** [comment]
Now that the Java benchmarks are in, do you want to tackle js @dianaclarke?

**Comment by dianaclarke** [comment]
Hi @domoritz:

I have a WIP pull request that adds the Arrow JS benchmarks: https://github.com/ursacomputing/benchmarks/pull/58
    
I have a few questions though.     
    
1) What are the units here? Seconds?


```
      "sampleResults": [
        0.00010663846170212765,
        0.00010678807659574467,
        0.00010785582231404959,
        0.0001081968326446281,
        0.00010857668936170212
      ]
```

2) I found the double usage of `name` in `"name": "name: ...` confusing.

    `"name": "name: 'lat', length: 1,000,000, type: Float32",`
    
    Perhaps `column` instead?
    
    `"name": "column: 'lat', length: 1,000,000, type: Float32",`

3) The names could be more informative. I see the following in the json.

```
    "name": "Table.from",
    "name": "readBatches",
    "name": "serialize",
    "name": "name: 'lat', length: 1,000,000, type: Float32",
    "name": "name: 'lng', length: 1,000,000, type: Float32",
    "name": "name: 'origin', length: 1,000,000, type: Dictionary<Int8, Utf8>",
    "name": "name: 'destination', length: 1,000,000, type: Dictionary<Int8, Utf8>",
    "name": "name: 'lat', length: 1,000,000, type: Float32",
    "name": "name: 'lng', length: 1,000,000, type: Float32",
    "name": "name: 'origin', length: 1,000,000, type: Dictionary<Int8, Utf8>",
    "name": "name: 'destination', length: 1,000,000, type: Dictionary<Int8, Utf8>",
    "name": "name: 'lat', length: 1,000,000, type: Float32",
    "name": "name: 'lng', length: 1,000,000, type: Float32",
    "name": "name: 'origin', length: 1,000,000, type: Dictionary<Int8, Utf8>",
    "name": "name: 'destination', length: 1,000,000, type: Dictionary<Int8, Utf8>",
    "name": "name: 'lat', length: 1,000,000, type: Float32",
    "name": "name: 'lng', length: 1,000,000, type: Float32",
    "name": "name: 'origin', length: 1,000,000, type: Dictionary<Int8, Utf8>",
    "name": "name: 'destination', length: 1,000,000, type: Dictionary<Int8, Utf8>",
    "name": "length: 1,000,000",
    "name": "name: 'lat', length: 1,000,000, type: Float32, test: gt, value: 0",
    "name": "name: 'lng', length: 1,000,000, type: Float32, test: gt, value: 0",
    "name": "name: 'origin', length: 1,000,000, type: Dictionary<Int8, Utf8>, test: eq, value: Seattle",
```

  Yet I do see informative names in the code (like `DataFrame Count By...` & `DataFrame Filter-Scan Count...`):

    - https://github.com/apache/arrow/blob/5ca16287a389afceabdd4b487d2e43e62745abcc/js/perf/index.ts#L124
    - https://github.com/apache/arrow/blob/5ca16287a389afceabdd4b487d2e43e62745abcc/js/perf/index.ts#L114
 
   Perhaps add the suite name? And make the values json rather than comma separated values as one string?
   
   Something like this:
   
       ...
       "name": "DataFrame Count By"
       "values": {
           "column": "lng",
           "length": "1,000,000",
           "type": "Float32",
           "test": "gt",
           "value": "0"
        }
        ...
    
Otherwise, we're pretty close, but the Ursa infra team would still need to add a bit of plumbing for the JS benchmarks.

**Comment by dianaclarke** [comment]
I've created the following ticket and I'll give it a shot now.

- [JS] Improve benchmark names
- https://issues.apache.org/jira/browse/ARROW-13266

**Comment by domoritz** [comment]
> What are the units here? Seconds?

Yes, seconds.

> [JS] Improve benchmark names, issues.apache.org/jira/browse/ARROW-13266

Thank you. https://github.com/apache/arrow/pull/10665 looks good. I approved it. 

Are you happy with the names now? Anything we can improve? 

> PS. I get the following error when I run the JS benchmarks. Any tips? Thanks!

I fixed the issue with `countBy` in https://github.com/apache/arrow/pull/10670. Good catch and I'm sorry I didn't catch this earlier.

**Comment by dianaclarke** [comment]
@domoritz Looks llke the JS benchmarks stopped working as of the following commit.

https://github.com/apache/arrow/commit/ba009fbd97cb32aa0edd2025d983dbe11de83b9b

```
$ yarn perf
yarn run v1.22.10
$ ts-node-transpile-only ./perf/index.ts
(node:49432) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/diana/workspace/arrow/js/perf/index.ts:22
import * as Arrow from '../src/Arrow';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Module.m._compile (/Users/diana/workspace/arrow/js/node_modules/ts-node/src/index.ts:1295:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/diana/workspace/arrow/js/node_modules/ts-node/src/index.ts:1298:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at Object.main (/Users/diana/workspace/arrow/js/node_modules/ts-node/src/bin.ts:246:14)

```

**Comment by domoritz** [comment]
Ups, I'll fix that. Can you try to set up the benchmarks with a previous version for now?

**Comment by domoritz** [comment]
Fixed in apache/arrow#10761

**Comment by domoritz** [comment]
Did this get closed accidentally?

**Comment by dianaclarke** [comment]
The work in this repo is done. @ElenaHenderson is working on the final infrastructure steps (in a private repo) that will execute the JavaScript benchmarks on each commit to the main branch of Arrow. I imagine that you'll start to see JavaScript benchmark results https://conbench.ursa.dev/ by end of week :)

**Comment by dianaclarke** [comment]
Oh! I'm already seeing JavaScript benchmark results coming in:

- https://conbench.ursa.dev/compare/runs/03ce7a3c734347b9947e228c467107ca...6087067222e24ffab8246bde5e267f4f/
- https://conbench.ursa.dev/benchmarks/f1e2413bf940498388e02712450a6175/

They will probably look a bit volatile until there is enough history to determine a normal range.

**Comment by domoritz** [comment]
Fantastic. Is there an overview page with all the js benchmarks and how they are evolving?

**Comment by domoritz** [comment]
@dianaclarke is there a way to run the benchmarks on a pull request like https://github.com/apache/arrow/pull/10371 automatically?

**Comment by dianaclarke** [comment]
@domoritz Can you try the following GitHub comment on your pull request.

`@ursabot please benchmark lang=JavaScript`

**Comment by domoritz** [comment]
Beautiful, thank you!

**Comment by dianaclarke** [comment]
PS. I just did the following on that pull request, so you know how to ask for help.

`@ursabot benchmark help`

**Comment by dianaclarke** [comment]
@domoritz I think I might have broken z-scores for pull requests with the following commit :(

https://github.com/conbench/conbench/commit/17b5f4831ba6d0b6e6826edb4629ed0127039518

So ignore this (zero up, zero down); instead look at the percent changed (for now), and click on the individual JavaScript benchmarks to see the pull request result in comparison to the distribution history.

<img width="249" alt="Screen Shot 2021-09-29 at 6 43 07 PM" src="https://user-images.githubusercontent.com/878798/135367485-9c4bebec-0704-416e-b0be-c769c09d9622.png">

I'll try to fix this on Friday (tomorrow is a holiday in Canada)

PS. I'll try to remember to look at these results too. Thanks for using Conbench!

**Comment by dianaclarke** [comment]
^^^ That was a false alarm. The z-scores are working correctly.
