### ISSUE TITLE
Add TPC-H benchmarks

### ISSUE THREAD

**Issue by jonkeane** [ursacomputing/benchmarks#80]
Now that https://github.com/ursacomputing/arrowbench/pull/33 is merged, could we add the TPC-H benchmarks?

The benchmark name is `tpc_h`, and it accepts the following parameters [the default values in {arrowbench}](https://github.com/ursacomputing/arrowbench/blob/main/R/bm-tpc-h.R#L14-L18) are what we would like to call:

* engine - "arrow"
* query_num - 1, 6
* format - "native", "parquet", "feather"
* scale - "1", "10"
* mem_map - FALSE (I believe you can leave this unspecified and it will take the default which is what we want — it only impacts the native benchmark regardless)

{arrowbench} automagically generates the TPC-H test data if it doesn't exist (and reuses it if it does), so we should not need to do anything to put the data anywhere. 

When I run all of these permutations on my computer (with maximum cores available, 3 iterations), they take a total of 2.9 minutes to run, so shouldn't add a _huge_ amount of time to our benchmark runs, though if we want to cut that down, we could remove one of the formats (either parquet or feather, they are pretty similar). 

We will be adding queries as we have the ability to run them, which I think will need PRs to benchmarks, but once we have the structure up it should be easy to add them in (they will each be added to the defaults in {arrowbench} as well).

**Comment by dianaclarke** [comment]
Done in:

- https://github.com/ursacomputing/benchmarks/pull/81
- https://github.com/ursacomputing/benchmarks/pull/82
- https://github.com/ursacomputing/benchmarks/pull/83
- https://github.com/ursacomputing/benchmarks/pull/84
